version: "3"

services:
  nginx:
    image: logxx/scoringsys-nginx
    container_name: scoringsys-nginx
    volumes:
      - cbtwww:/var/www/certbot/:ro
      - cbtconf:/etc/nginx/ssl/:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
    restart: always
  frontend:
    image: logxx/scoringsys-front
    container_name: scoringsys-front
    environment:
      - BACKEND_HOST=backend
      - FLET_PORT=50422
      - PYTHONUNBUFFERED=1
    expose:
      - 50422
    depends_on:
      - backend
    restart: always
  backend:
    image: logxx/scoringsys-back
    container_name: scoringsys-back
    environment:
      - FRONTEND_HOST=frontend
      - FRONTEND_PORT=50422
      - DATA_HOST=ml
      - DATA_PORT=8888
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
      - UVICORN_ROOT_PATH=/api
    expose:
      - 8000
    restart: always
  ml:
    image: logxx/scoringsys-ml
    container_name: scoringsys-ml
    environment:
    - UVICORN_HOST=0.0.0.0
    - UVICORN_PORT=8888
    expose:
      - 8888
    restart: always
  duckdns:
    image: lscr.io/linuxserver/duckdns
    container_name: scoringsys-duckdns
    environment:
      - SUBDOMAINS=scoringsys
      - TOKEN=${DUCKDNS_TOKEN}
    restart: always
  certbot:
    image: certbot/certbot
    container_name: scoringsys-certbot
    volumes:
      - cbtwww:/var/www/certbot:rw
      - cbtconf:/etc/letsencrypt/:rw
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/certbot --email ${CERT_EMAIL} --agree-tos --no-eff-email -d scoringsys.duckdns.com
volumes:
  cbtwww:
  cbtconf: