name: ci 
on:
  push:
    branches: ["development"]
    paths:
      - app/**
      - terraform/**
      - ansible/**
      - .github/workflows/pylint.yml
      - .github/workflows/docker.yml
      - .github/workflows/ansible.yml
      - .github/workflows/terraform.yml

jobs:
  #  pylint:
  #   uses: ./.github/workflows/pylint.yml
  docker:
  #  needs: [pylint]
    uses: ./.github/workflows/docker.yml
    secrets: inherit
  terraform:
    uses: ./.github/workflows/terraform.yml
    secrets: inherit
  ansible:
    needs: [docker, terraform]
    uses: ./.github/workflows/ansible.yml
    secrets: inherit
