name: deploy 
on: workflow_dispatch

jobs:
  pylint:
    uses: ./.github/workflows/pylint.yml
  docker:
  #  needs: [pylint]
    uses: ./.github/workflows/docker.yml
    secrets: inherit
  terraform:
    uses: ./.github/workflows/terraform.yml
    secrets: inherit
  ansible:
    needs: [docker, terraform]
    uses: ./.github/workflows/ansible.yml
    with:
      external_ip: ${{ needs.terraform.outputs.external_ip }}
    secrets: inherit
