name: ci

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWD }}
      -
        name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: app/frontend/
          push: true
          tags: logxx/scoringsys-front:latest
      -
        name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: app/backend/
          push: true
          tags: logxx/scoringsys-back:latest
      -
        name: Build and push ml service
        uses: docker/build-push-action@v4
        with:
          context: app/ML/
          push: true
          tags: logxx/scoringsys-ml:latest
