name: docker build and push
on: 
  push:
    paths:
      - app/**
jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        docker-app: [nginx, frontend, backend, ml]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWD }}
      - name: Build and push scoringsys-${{ matrix.docker-app }}
        uses: docker/build-push-action@v4
        with:
          context: ./app/${{ matrix.docker-app }}/
          push: true
          tags: ${{ secrets.DOCKER_LOGIN }}/scoringsys-${{ matrix.docker-app }}:latest
          cache-from: type=gha,scope=${{ matrix.docker-app }}
          cache-to: type=gha,mode=max,scope=${{ matrix.docker-app }}
