name: docker build and push
on: 
  push:
    paths:
      - app/**
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWD }}
      -
        name: Build and push nginx copy
        uses: docker/build-push-action@v4
        with:
          context: ./app/nginx/
          push: true
          tags: ${{ secrets.DOCKER_LOGIN }}/scoringsys-nginx:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: ./app/frontend/
          push: true
          tags: ${{ secrets.DOCKER_LOGIN }}/scoringsys-front:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: ./app/backend/
          push: true
          tags: ${{ secrets.DOCKER_LOGIN }}/scoringsys-back:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Build and push ml service
        uses: docker/build-push-action@v4
        with:
          context: ./app/ML/
          push: true
          tags: ${{ secrets.DOCKER_LOGIN }}/scoringsys-ml:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
