name: 'Terraform deploy'

on: 
  workflow_call:
    outpus:
      external_ip:
        description: "The ip of created instance"
        value: ${{ jobs.terraform.outputs.external_ip }}

jobs:
  terraform:
    runs-on: ubuntu-latest

    outputs:
      external_ip: 
        value: ${{ steps.tfapply.outputs.external_ip }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init --backend-config="access_key=${{secrets.S3_ACCESS}}" --backend-config="secret_key=${{secrets.S3_SECRET}}"
      working-directory: ./terraform

    - name: Terraform Format
      run: terraform fmt -check
      working-directory: ./terraform

    - name: Prepare yandex key 
      run: |
        touch /home/runner/key.json
        chmod 700 /home/runner/key.json
        echo '${{secrets.YANDEX_KEY}}' > /home/runner/key.json

    - name: Terraform Plan
      run: terraform plan --input=false --var="service_token=/home/runner/key.json"
      working-directory: ./terraform

    - name: Terraform Apply
      id: tfapply
      run: terraform apply --auto-approve --input=false --var="service_token=/home/runner/key.json"
      working-directory: ./terraform
