name: 'Terraform deploy'

on:
  push:
    branches: [ "development" ]
    paths:
      - terraform/**
      - .github/workflows/terraform.yml

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init --backend-config="access_key=${{secrets.S3_ACCESS}}" --backend-config="secret_key=${{secrets.S3_SECRET}}"
      working-directory: ./terraform

    - name: Terraform Format
      run: terraform fmt -check
      working-directory: ./terraform

    - name: Prepare Yandex key
      run: |
        touch key.json
        chmod 700 key.json
        echo -e ${{secrets.YANDEX_KEY}} > key.json

    - name: Terraform Plan
      run: terraform plan -input=false -var="service_key_path=key.json"
      working-directory: ./terraform

    - name: Terraform Apply
      id: tfapply
      run: terraform apply -auto-approve -input=false -var="service_key_path=key.json"
      working-directory: ./terraform
    - name: Save host
      run: echo "ANSIBLE_HOST=${{steps.tfapply.outputs.external_ip}}" >> $GITHUB_ENV
  ansible:
    uses: ./.github/workflows/ansible.yml
